// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhcTixdrjumUKQfPgGKjf9u4USh2ga48A',
    appId: '1:345699091866:web:e15c3faf9baf9d8777e623',
    messagingSenderId: '345699091866',
    projectId: 'fruit-hup-d4206',
    authDomain: 'fruit-hup-d4206.firebaseapp.com',
    storageBucket: 'fruit-hup-d4206.firebasestorage.app',
    measurementId: 'G-VNNVM1KKR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVZULpVn9gG7GVF-pFITrGm8FalP2qgo',
    appId: '1:345699091866:android:a4a6070add12ee9077e623',
    messagingSenderId: '345699091866',
    projectId: 'fruit-hup-d4206',
    storageBucket: 'fruit-hup-d4206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAO1V5HWR5dyyps3UBWp5tRaHKYQszEZo',
    appId: '1:345699091866:ios:156f3b3baefaf3d277e623',
    messagingSenderId: '345699091866',
    projectId: 'fruit-hup-d4206',
    storageBucket: 'fruit-hup-d4206.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAO1V5HWR5dyyps3UBWp5tRaHKYQszEZo',
    appId: '1:345699091866:ios:156f3b3baefaf3d277e623',
    messagingSenderId: '345699091866',
    projectId: 'fruit-hup-d4206',
    storageBucket: 'fruit-hup-d4206.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhcTixdrjumUKQfPgGKjf9u4USh2ga48A',
    appId: '1:345699091866:web:6155962db6723cd877e623',
    messagingSenderId: '345699091866',
    projectId: 'fruit-hup-d4206',
    authDomain: 'fruit-hup-d4206.firebaseapp.com',
    storageBucket: 'fruit-hup-d4206.firebasestorage.app',
    measurementId: 'G-QM1TK9WDJ6',
  );
}
